
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\amiri\PycharmProjects\kursach\frames\frame register")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("955x463")
window.configure(bg = "#C4E0A6")


canvas = Canvas(
    window,
    bg = "#C4E0A6",
    height = 463,
    width = 955,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    529.0,
    0.0,
    955.0,
    463.0,
    fill="#74C38C",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    745.5,
    328,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#8BDEA5",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=615.0,
    y=308.0,
    width=261.0,
    height=41.0
)

canvas.create_text(
    607.0,
    276.0,
    anchor="nw",
    text="Начальный баланс",
    fill="#000000",
    font=("Inter SemiBold", 18 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    741.5,
    133,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#8BDEA5",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=611.0,
    y=113.0,
    width=261.0,
    height=41.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    745.5,
    232,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#8BDEA5",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=615.0,
    y=211.0,
    width=261.0,
    height=41.0
)

canvas.create_text(
    613.0,
    83.0,
    anchor="nw",
    text="Логин",
    fill="#000000",
    font=("Inter SemiBold", 18 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    241.0,
    225.0,
    image=image_image_1
)

canvas.create_text(
    613.0,
    178.0,
    anchor="nw",
    text="Пароль",
    fill="#000000",
    font=("Inter SemiBold", 18 * -1)
)

canvas.create_text(
    644.0,
    24.0,
    anchor="nw",
    text="Регистрация",
    fill="#000000",
    font=("Inter SemiBold", 30 * -1)
)

canvas.create_rectangle(
    526.0,
    -3.0,
    529.0,
    463.0,
    fill="#000000",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=648.0,
    y=381.0,
    width=188.0,
    height=42.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    267.0208740234375,
    247.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
