
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\amiri\PycharmProjects\kursach\frames\frame settings")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("762x637")
window.configure(bg = "#C4E0A6")


canvas = Canvas(
    window,
    bg = "#C4E0A6",
    height = 637,
    width = 762,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    125.0,
    762.0,
    445.0,
    fill="#74C38C",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    229.5,
    371.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#8FEAAB",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=154.0,
    y=350.0,
    width=151.0,
    height=43.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    225.0,
    328.0,
    image=image_image_1
)

canvas.create_rectangle(
    -2.0,
    123.0,
    761.9999901050287,
    125.99999999027409,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    -2.0,
    443.0,
    761.9999901050287,
    445.9999999902741,
    fill="#000000",
    outline="")


entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    229.5,
    256.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#8FEAAB",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=154.0,
    y=235.0,
    width=151.0,
    height=43.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    222.0,
    213.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    181.0,
    67.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    384.0,
    163.0,
    image=image_image_4
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=389.0,
    y=493.0,
    width=299.0,
    height=79.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=72.0,
    y=493.0,
    width=299.0,
    height=79.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=427.0,
    y=267.0,
    width=190.0,
    height=58.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=522.0,
    y=38.0,
    width=187.0,
    height=62.33333206176758
)
window.resizable(False, False)
window.mainloop()
