
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/build/assets/frame SummaOpisanie")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("439x414")
window.configure(bg = "#C4E0A6")


canvas = Canvas(
    window,
    bg = "#C4E0A6",
    height = 414,
    width = 439,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    -6.499937485792088,
    89.73707292562653,
    549.0001250284158,
    101.26293562568912,
    fill="#63BD03",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    220.0,
    173.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#8FEAAB",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=89.0,
    y=155.0,
    width=262.0,
    height=39.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    220.0,
    266.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#8FEAAB",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=89.0,
    y=248.0,
    width=262.0,
    height=39.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    219.0,
    56.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    121.0,
    134.0,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=132.0,
    y=312.0,
    width=175.0,
    height=39.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    220.0,
    227.0,
    image=image_image_3
)
window.resizable(False, False)
window.mainloop()
